/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/Drawer/AmortizacionCalculada`; params?: Router.UnknownInputParams; } | { pathname: `/Drawer/EditPerson`; params?: Router.UnknownInputParams; } | { pathname: `/Drawer/FormIngresos`; params?: Router.UnknownInputParams; } | { pathname: `/Drawer/Home`; params?: Router.UnknownInputParams; } | { pathname: `/Drawer/Personas`; params?: Router.UnknownInputParams; } | { pathname: `/Drawer/register`; params?: Router.UnknownInputParams; } | { pathname: `/Drawer/Search`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/Drawer/AmortizacionCalculada`; params?: Router.UnknownOutputParams; } | { pathname: `/Drawer/EditPerson`; params?: Router.UnknownOutputParams; } | { pathname: `/Drawer/FormIngresos`; params?: Router.UnknownOutputParams; } | { pathname: `/Drawer/Home`; params?: Router.UnknownOutputParams; } | { pathname: `/Drawer/Personas`; params?: Router.UnknownOutputParams; } | { pathname: `/Drawer/register`; params?: Router.UnknownOutputParams; } | { pathname: `/Drawer/Search`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/Drawer/AmortizacionCalculada${`?${string}` | `#${string}` | ''}` | `/Drawer/EditPerson${`?${string}` | `#${string}` | ''}` | `/Drawer/FormIngresos${`?${string}` | `#${string}` | ''}` | `/Drawer/Home${`?${string}` | `#${string}` | ''}` | `/Drawer/Personas${`?${string}` | `#${string}` | ''}` | `/Drawer/register${`?${string}` | `#${string}` | ''}` | `/Drawer/Search${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/Drawer/AmortizacionCalculada`; params?: Router.UnknownInputParams; } | { pathname: `/Drawer/EditPerson`; params?: Router.UnknownInputParams; } | { pathname: `/Drawer/FormIngresos`; params?: Router.UnknownInputParams; } | { pathname: `/Drawer/Home`; params?: Router.UnknownInputParams; } | { pathname: `/Drawer/Personas`; params?: Router.UnknownInputParams; } | { pathname: `/Drawer/register`; params?: Router.UnknownInputParams; } | { pathname: `/Drawer/Search`; params?: Router.UnknownInputParams; };
    }
  }
}
